In [1]:
import pandas as pd
print('Setup completed!')

Setup completed!

In [2]:
train = pd.read_parquet('/kaggle/input/avitotech-ml-cup-2024-train-dataset')
campaigns = pd.read_parquet('/kaggle/input/avitotech-ml-cup-2024-campaigns-meta-dataset')
print('\'Train\' and \'Campaigns\' datasets have been successfully read!')

'Train' and 'Campaigns' datasets have been successfully read!

In [3]:
train['target'] = train['target'].astype(bool)
train['event_date'] = train['event_date'].astype('datetime64[ns]')
print('success')

success

In [4]:
campaigns['start_date'] = campaigns['start_date'].astype('datetime64[ns]')
campaigns['end_date'] = campaigns['end_date'].astype('datetime64[ns]')
print('success')

success

In [5]:
train = train.merge(campaigns, on='adv_campaign_id', how='inner')
train.head(10)

,user_id,adv_campaign_id,platform_id,adv_creative_id,event_date,banner_code,is_main,target,start_date,end_date,goal_cost,goal_budget,location_id,logcat_id
0,2853707,3352,3,3075,2024-09-17,6,True,False,2024-09-16,2024-09-25,5.131051,2647.795831,9,56
1,2537244,4029,2,3260,2024-09-17,8,True,False,2024-09-16,2024-09-22,4.931622,6953.261023,46,65
2,63033,1578,3,1109,2024-09-17,6,True,False,2024-09-04,2024-09-18,3.711480,7035.724050,1,65
3,164702,3434,1,1079,2024-09-17,7,True,False,2024-09-17,2024-09-24,4.030369,5034.412852,47,65
4,2802905,2208,3,3576,2024-09-17,6,True,False,2024-09-16,2024-09-22,4.931534,7024.725026,46,65
5,2253637,2001,2,1984,2024-09-17,8,True,False,2024-09-12,2024-09-18,10.903505,16173.546557,30,25
6,562985,3559,4,3614,2024-09-17,4,True,False,2024-09-17,2024-09-23,12.095901,19259.422080,30,25
7,683880,1848,2,3205,2024-09-17,8,True,False,2024-09-12,2024-09-18,4.403577,4072.374707,30,51
8,999311,1842,2,94,2024-09-17,8,True,False,2024-09-17,2024-09-23,3.962750,7762.308382,58,65
9,1496528,3895,2,3856,2024-09-17,8,True,False,2024-09-16,2024-09-22,4.191298,9741.874240,54,18

In [6]:
del campaigns
print('\'Campaigns\' dataset has been deleted.')

'Campaigns' dataset has been deleted.

In [7]:
train['start_date'] = ((train['event_date'] - train['start_date']) / 86400000000000).astype(int)
train['end_date'] = ((train['end_date'] - train['event_date']) / 86400000000000).astype(int)
train['goal_cost'] = train['goal_budget'] / train['goal_cost']
train.head(10)

,user_id,adv_campaign_id,platform_id,adv_creative_id,event_date,banner_code,is_main,target,start_date,end_date,goal_cost,goal_budget,location_id,logcat_id
0,2853707,3352,3,3075,2024-09-17,6,True,False,1,8,516.033842,2647.795831,9,56
1,2537244,4029,2,3260,2024-09-17,8,True,False,1,5,1409.933926,6953.261023,46,65
2,63033,1578,3,1109,2024-09-17,6,True,False,13,1,1895.665274,7035.724050,1,65
3,164702,3434,1,1079,2024-09-17,7,True,False,0,7,1249.119717,5034.412852,47,65
4,2802905,2208,3,3576,2024-09-17,6,True,False,1,5,1424.450176,7024.725026,46,65
5,2253637,2001,2,1984,2024-09-17,8,True,False,5,1,1483.334638,16173.546557,30,25
6,562985,3559,4,3614,2024-09-17,4,True,False,0,6,1592.227210,19259.422080,30,25
7,683880,1848,2,3205,2024-09-17,8,True,False,5,1,924.787899,4072.374707,30,51
8,999311,1842,2,94,2024-09-17,8,True,False,0,6,1958.818711,7762.308382,58,65
9,1496528,3895,2,3856,2024-09-17,8,True,False,1,5,2324.309872,9741.874240,54,18

In [8]:
i = 0
step = 10_000_000
ind = 1
while i < len(train):
    j = i + step
    name = f'train_{ind}'
    train_part = train.iloc[i:j]
    train_part = train_part.drop(columns=['event_date']) \
                           .rename(columns={
                               'start_date': 'days_from_start',
                               'end_date'  : 'days_to_end',
                               'goal_cost' : 'goals_number'
                           })
    train_part.to_parquet(f'/kaggle/working/{name}.parquet')
    del train_part
    print(f'\'{name}\' dataset has been formed and written.')
    i += step
    ind += 1

'train_1' dataset has been formed and written.
'train_2' dataset has been formed and written.
'train_3' dataset has been formed and written.
'train_4' dataset has been formed and written.
'train_5' dataset has been formed and written.
'train_6' dataset has been formed and written.
'train_7' dataset has been formed and written.
'train_8' dataset has been formed and written.
'train_9' dataset has been formed and written.
'train_10' dataset has been formed and written.
'train_11' dataset has been formed and written.
'train_12' dataset has been formed and written.